### PR TITLE
Show visited article history

### PR DESCRIPTION
**Pull request by FaFre**
This PR adds functionality to display recently visited articles (which helps the memory sometimes).

It utilizes the already existing logging for visited articles, with the difference that with this PR the actual time is additionally getting persisted. Everything is backward compatible to existing persisted visits.

The history page is basically c&p from favorites.

Everything is working already but there might be some further requirements like:
- Layout of the history list with date doesn't look pretty yet
- (Maybe) Settings to show/hide the history page, and also to optionally clear the history

I also added the Linux platform to the project, and updated the existing platforms.

### CODE REVIEW

**Comment by Mosc** [comment]
Ooh, interesting. Haven't had time to go through all the changes yet, but some initial comments:

- I like the idea of a history page, but I'm not convinced it needs to be shown prominently enough that it deserves a spot in the navigation bar. How do you feel about putting it in the action bar overflow menu instead?
- I see you'd like to add the visited date, but that feels optional and I'm kinda finicky about the way it'll look. Just having a page that shows the IDs for the first implementation would simplify the PR by a lot!
- The Linux support and platform files updates belong in a separate PR.

**Comment by FaFre** [comment]
Initially I implemented this for private use only, that's why things are still a bit mixed up and I just created this draft to see what happens.

> Ooh, interesting. Haven't had time to go through all the changes yet, but some initial comments:
> 
>     * I like the idea of a history page, but I'm not convinced it needs to be shown prominently enough that it deserves a spot in the navigation bar. How do you feel about putting it in the action bar overflow menu instead?
Yep, sounds good to me.
> 
>     * I see you'd like to add the visited date, but that feels optional and I'm kinda finicky about the way it'll look. Just having a page that shows the IDs for the first implementation would simplify the PR by a lot!
Can you give me some feedback on how the page and widget tree itself? It's just c&p from fav page. Is this ok, or should we try to find a more generic approach here?
> 
>     * The Linux support and platform files updates belong in a separate PR.
done

**Comment by Mosc** [comment]
I think copying the favorites page is fine for now, actually. That's how most of the pages in the app have been built. If you have ideas on how we can generalize the implementation that could be useful, but is probably best left for a separate PR as well to keep changes atomic.

**Comment by FaFre** [comment]
@Mosc I was rethinking the complete implementation and actually it will be pretty limited. What do you think about implementing the wallabag API to save articles instead? Wallabag (https://github.com/wallabag/wallabag) is a self hosted open source solution to pocket. The neat thing is that KOreader also has implemented the API and it would make it very easy to actually push articles from Glider app directly onto the ebook reader for example.

**Pull request closed without merging**
